server:
  port: 8082

spring:
  application:
    name: microservice-poc-product
  data:
    mongodb:
      host: localhost
      port: 27017
#      username: <DB-USERNAME>
#      password: <DB-PASSWORD>
      database: shopping
      repositories:
        eneable: true

  zipkin:
    base-url: http://localhost:9411/



