server:
  port: 8082

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
#      username: <DB-USERNAME>
#      password: <DB-PASSWORD>
      database: shopping
      repositories:
        eneable: true



