server:
  port: 8083

spring:
  application:
    name: microservice-poc-cart
  data:
    mongodb:
      host: localhost
      port: 27017
#      username: <DB-USERNAME>
#      password: <DB-PASSWORD>
      database: shopping
      repositories:
        eneable: true

  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka



