server:
  port: 8081

spring:
  application:
    name: microservice-poc-user
  data:
    mongodb:
      host: localhost
      port: 27017
#      username: <DB-USERNAME>
#      password: <DB-PASSWORD>
      database: shopping
      repositories:
        eneable: true
  zipkin:
    base-url: http://localhost:9411/

rest:
  endpoint:
    cartByUserId: http://localhost:8083/cart/user/{userId}
    productInfoByProductIdList: http://localhost:8082/product/product-info



