server:
  port: 8081

spring:
  application:
    name: microservice-poc-user
  data:
    mongodb:
      host: localhost
      port: 27017
#      username: <DB-USERNAME>
#      password: <DB-PASSWORD>
      database: shopping
      repositories:
        eneable: true
  zipkin:
    base-url: http://localhost:9411/

rest:
  endpoint:
    cartByUserId: http://microservice-poc-cart/cart/user/{userId}
    productInfoByProductIdList: http://microservice-poc-product/product/product-info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka



